export const SELL_APPEAL_RESULTS = {
  SELL_MCWIN_SUCCESS: 'SELL_MCWIN_SUCCESS',
  SELL_EUWIN_CANCEL_MC_VIOLATE: 'SELL_EUWIN_CANCEL_MC_VIOLATE',
  SELL_NOWIN_CANCEL_MC_HAS_RETURNED: 'SELL_NOWIN_CANCEL_MC_HAS_RETURNED'
}

export const BUY_APPEAL_RESULTS = {
  BUY_MCWIN_CANCEL: 'BUY_MCWIN_CANCEL',
  BUY_EUWIN_REOPEN: 'BUY_EUWIN_REOPEN',
  BUY_EUWIN_FORCE_CLOSE: 'BUY_EUWIN_FORCE_CLOSE',
  BUY_EUWIN_CANCEL_MC_VIOLATE: 'BUY_EUWIN_CANCEL_MC_VIOLATE',
  BUY_NOWIN_CANCEL_EVIDENT_NOT_APPROVED: 'BUY_NOWIN_CANCEL_EVIDENT_NOT_APPROVED',
  BUY_NOWIN_CANCEL_MC_HAS_RETURNED: 'BUY_NOWIN_CANCEL_MC_HAS_RETURNED'
}

export const SELL_APPEAL_RESULTS_KEY = {
  SELL_MCWIN_SUCCESS: 1,
  SELL_EUWIN_CANCEL_MC_VIOLATE: 2,
  SELL_NOWIN_CANCEL_MC_HAS_RETURNED: 3
}

export const BUY_APPEAL_RESULTS_KEY = {
  BUY_MCWIN_CANCEL: 1,
  BUY_EUWIN_REOPEN: 2,
  BUY_EUWIN_FORCE_CLOSE: 3,
  BUY_EUWIN_CANCEL_MC_VIOLATE: 4,
  BUY_NOWIN_CANCEL_EVIDENT_NOT_APPROVED: 5,
  BUY_NOWIN_CANCEL_MC_HAS_RETURNED: 6
}

export const MODAL_TYPE_CONFIRM = {
  MERCHANT_WIN: 'merchant_win',
  USER_WIN: 'user_win',
  CLOSE_APPEAL: 'close_appeal',
  FORCE_CLOSE_APPEAL: 'force_close_appeal',
  OPEN_TRANSACTION: 'open_transaction'
}

export const APPEAL_STATUS = {
  PREPARE: 'PREPARE',
  OPEN: 'OPEN',
  PENDING: 'PENDING',
  CLOSE: 'CLOSE'
}
