export const CHAT_USER_TYPE = {
  USER: 'USER',
  SYSTEM: 'SYSTEM',
  BOT: 'BOT',
  ADMIN: 'ADMIN',
  SUPPORTER_CHAT: 'SUPPORTER_CHAT'
}

export const CHAT_MESSAGE_TYPE = {
  RAW: 'RAW',
  ATTACHMENT: 'ATTACHMENT'
}

export const CHAT_WS_EVENT = {
  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  CLOSE_ROOM: 'CLOSE_ROOM',
  MESSAGE: 'MESSAGE',
  SEEN_MESSAGE: 'SEEN_MESSAGE',
  EXCEPTION: 'exception'
}

export const FILE_SIZE_LIMIT_CHAT = 1024 * 1024 * 5

export const CHAT_MESSAGE_MAX_LENGTH = {
  SMALL: 200,
  NORMAL: 1000
}

export const TYPE_ROLE_CHAT = {
  BUYER: 'BUYER',
  SELLER: 'SELLER',
  SUPPORTER_CHAT: 'SUPPORTER_CHAT'
}
