export const CUSTOMER_SUPPORT_TYPE = {
  ORDER: 1,
  TRANSACTION: 2,
  APPEAL: 3,
  REGISTRATION_MANAGER: 4,
  SYSTEM: 5,
  OTHER: 6
}

export const CUSTOMER_SUPPORT_STEP = {
  RECEIVED: 'RECEIVED',
  PENDING: 'PENDING'
}

export const CUSTOMER_SUPPORT_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED'
}

export const CUSTOMER_SUPPORT_STATE = {
  NEW: 'NEW',
  OLD: 'OLD'
}
