import { ORDER_STATUS } from '@/config/constant';

export const BUY_ORDER_STEPS = {
  BUY_ORDER_CREATED_BY_USER: 'BUY_ORDER_CREATED_BY_USER',
  BUY_ORDER_CREATED_BY_USER_DEAL_TIME: 'BUY_ORDER_CREATED_BY_USER_DEAL_TIME',
  BUY_NOTIFY_SENT_FIAT_BY_USER: 'BUY_NOTIFY_SENT_FIAT_BY_USER',
  BUY_NOTIFY_SENT_FIAT_BY_USER_DEAL_TIME: 'BUY_NOTIFY_SENT_FIAT_BY_USER_DEAL_TIME',
  BUY_ENABLE_APPEAL_WHILE_SENDING_FIAT: 'BUY_ENABLE_APPEAL_WHILE_SENDING_FIAT',
  BUY_ENABLE_APPEAL_WHILE_CONFIRMING_FIAT_BY_MERCHANT: 'BUY_ENABLE_APPEAL_WHILE_CONFIRMING_FIAT_BY_MERCHANT',
  BUY_APPEAL_SENT_WHILE_CONFIRMING_FIAT_BY_MERCHANT: 'BUY_APPEAL_SENT_WHILE_CONFIRMING_FIAT_BY_MERCHANT',
  BUY_CONFIRMED_FIAT_BY_MERCHANT: 'BUY_CONFIRMED_FIAT_BY_MERCHANT',
  BUY_ENABLE_APPEAL_WHEN_CONFIRMED_FIAT_BY_MERCHANT: 'BUY_ENABLE_APPEAL_WHEN_CONFIRMED_FIAT_BY_MERCHANT',
  BUY_SENT_FIAT_APPEAL_BY_USER: 'BUY_SENT_FIAT_APPEAL_BY_USER',
  BUY_CONFIRMED_FIAT_BY_MERCHANT_DEAL_TIME: 'BUY_CONFIRMED_FIAT_BY_MERCHANT_DEAL_TIME',
  BUY_SENDING_CRYPTO_BY_MERCHANT: 'BUY_SENDING_CRYPTO_BY_MERCHANT',
  BUY_SENDING_CRYPTO_FAILED: 'BUY_SENDING_CRYPTO_FAILED',
  BUY_SENDING_CRYPTO_FAILED_APPEAL_BY_USER: 'BUY_SENDING_CRYPTO_FAILED_APPEAL_BY_USER',
  BUY_APPEAL_SENT_SENDING_CRYPTO_FAILED: 'BUY_APPEAL_SENT_SENDING_CRYPTO_FAILED',
  BUY_SENDING_CRYPTO_SUCCESS: 'BUY_SENDING_CRYPTO_SUCCESS',
  BUY_ORDER_CANCELLED_BY_USER: 'BUY_ORDER_CANCELLED_BY_USER',
  BUY_ORDER_CANCELLED_BY_SYSTEM: 'BUY_ORDER_CANCELLED_BY_SYSTEM'
}

export const SELL_ORDER_STEPS = {
  SELL_ORDER_CREATED_BY_USER: 'SELL_ORDER_CREATED_BY_USER',
  SELL_SENDING_CRYPTO_BY_USER: 'SELL_SENDING_CRYPTO_BY_USER',
  SELL_SENDING_CRYPTO_FAILED: 'SELL_SENDING_CRYPTO_FAILED',
  SELL_SENDING_CRYPTO_SUCCESS: 'SELL_SENDING_CRYPTO_SUCCESS',
  SELL_SENDING_CRYPTO_SUCCESS_DEAL_TIME: 'SELL_SENDING_CRYPTO_SUCCESS_DEAL_TIME',
  SELL_NOTIFY_SENT_FIAT_BY_MERCHANT_DEAL_TIME: 'SELL_NOTIFY_SENT_FIAT_BY_MERCHANT_DEAL_TIME',
  SELL_ENABLE_APPEAL_NOTIFY_SENT_FIAT_BY_MERCHANT: 'SELL_ENABLE_APPEAL_NOTIFY_SENT_FIAT_BY_MERCHANT',
  SELL_APPEAL_SENT_FIAT_NOT_RECEIVED_BY_USER: 'SELL_APPEAL_SENT_FIAT_NOT_RECEIVED_BY_USER',
  // status: CONFIRM_PAID
  SELL_NOTIFY_SENT_FIAT_BY_MERCHANT: 'SELL_NOTIFY_SENT_FIAT_BY_MERCHANT',
  SELL_APPEALING_USER_NOT_RECEIVE_FIAT: 'SELL_APPEALING_USER_NOT_RECEIVE_FIAT',
  SELL_ENABLE_APPEAL_WITH_ADMIN_USER_NOT_RECEIVE_FIAT: 'SELL_ENABLE_APPEAL_WITH_ADMIN_USER_NOT_RECEIVE_FIAT',
  SELL_APPEALING_WITH_ADMIN_USER_NOT_RECEIVE_FIAT: 'SELL_APPEALING_WITH_ADMIN_USER_NOT_RECEIVE_FIAT',
  // status: COMPLETED
  SELL_CONFIRMED_FIAT_BY_USER: 'SELL_CONFIRMED_FIAT_BY_USER',
  SELL_ORDER_CANCELLED_BY_USER: 'SELL_ORDER_CANCELLED_BY_USER',
  SELL_ORDER_CANCELLED_BY_SYSTEM: 'SELL_ORDER_CANCELLED_BY_SYSTEM'
}

export const SUB_KEY_DESCRIPTION_STEP = {
  CHAT: 'chat',
  TIMEOUT: 'timeout',
  COUNTDOWN: 'countdown',
  APPEAL: 'appeal'
}

export const STEPS_COUNTDOWN = [
  BUY_ORDER_STEPS.BUY_ORDER_CREATED_BY_USER,
  BUY_ORDER_STEPS.BUY_ORDER_CREATED_BY_USER_DEAL_TIME,
  BUY_ORDER_STEPS.BUY_NOTIFY_SENT_FIAT_BY_USER,
  BUY_ORDER_STEPS.BUY_NOTIFY_SENT_FIAT_BY_USER_DEAL_TIME,
  BUY_ORDER_STEPS.BUY_ENABLE_APPEAL_WHILE_CONFIRMING_FIAT_BY_MERCHANT,
  BUY_ORDER_STEPS.BUY_CONFIRMED_FIAT_BY_MERCHANT,
  BUY_ORDER_STEPS.BUY_CONFIRMED_FIAT_BY_MERCHANT_DEAL_TIME,
  SELL_ORDER_STEPS.SELL_ORDER_CREATED_BY_USER,
  SELL_ORDER_STEPS.SELL_SENDING_CRYPTO_BY_USER,
  SELL_ORDER_STEPS.SELL_SENDING_CRYPTO_FAILED,
  SELL_ORDER_STEPS.SELL_SENDING_CRYPTO_SUCCESS,
  SELL_ORDER_STEPS.SELL_SENDING_CRYPTO_SUCCESS_DEAL_TIME,
  SELL_ORDER_STEPS.SELL_NOTIFY_SENT_FIAT_BY_MERCHANT_DEAL_TIME,
  SELL_ORDER_STEPS.SELL_ENABLE_APPEAL_NOTIFY_SENT_FIAT_BY_MERCHANT
]

export const ORDER_APPEAL_KEY_LANG = {
  USER: 'user_orders',
  MERCHANT: 'merchant'
}

export const ORDER_STATUS_CLASS_NAME = {
  [ORDER_STATUS.TO_BE_PAID]: 'danger',
  [ORDER_STATUS.PAID]: 'success'
}

export const ORDER_FIELD_SEARCH_GROUP = {
  ID: 'orderId',
  REF_ID: 'refId',
  TOTAL_PRICE: 'totalPrice',
  TRANS_CODE: 'transCode',
  WALLET_ADDRESS: 'WALLET_ADDRESS',
  NICK_NAME: 'NICK_NAME',
  POST_REFID: 'POST_REFID'
}

export const ORDER_FIELD_SEARCH_DEFAULT = [
  ORDER_FIELD_SEARCH_GROUP.REF_ID,
  ORDER_FIELD_SEARCH_GROUP.TOTAL_PRICE,
  ORDER_FIELD_SEARCH_GROUP.TRANS_CODE
]

export const ORDER_CANCEL_REASON = 'TX_HASH_EXCEED_LIMIT'

export const DATE_RANGE_FIELD_SEARCH_GROUP = {
  CREATED_AT: 'createdAt',
  LAST_TRADE_AT: 'lastTradeAt',
  LAST_LOGIN_AT: 'lastLoginAt',
  CHECK_IN: 'CHECK_IN',
  CHECK_OUT: 'CHECK_OUT'
}
