export const REPORT_TYPE = {
  ORDER_HISTORIES: 'ORDER_HISTORIES',
  POST_HISTORIES: 'POST_HISTORIES',
  REVENUE: 'REVENUE',
  ASSET: 'ASSET',
  MANAGER_STATISTIC: 'MANAGER_STATISTIC',
  TRADE_TYPE_DIFFERENCE: 'TRADE_TYPE_DIFFERENCE',
  STAFF_STATISTIC: 'STAFF_STATISTIC',
  USER_STATISTIC: 'USER_STATISTIC',
  SHIFT_LOGS: 'SHIFT_LOGS'
}

export const REPORT_NAMING_FILE = {
  [REPORT_TYPE.ORDER_HISTORIES]: 'Order_History',
  [REPORT_TYPE.POST_HISTORIES]: 'Post_History',
  [REPORT_TYPE.REVENUE]: 'Manager_Revenue',
  [REPORT_TYPE.ASSET]: 'Asset_statistics',
  [REPORT_TYPE.MANAGER_STATISTIC]: 'Manager_Statistics',
  [REPORT_TYPE.TRADE_TYPE_DIFFERENCE]: 'Profit&loss_statement',
  [REPORT_TYPE.STAFF_STATISTIC]: 'Staff_Statistics',
  [REPORT_TYPE.USER_STATISTIC]: 'EndUser_Statistics',
  [REPORT_TYPE.SHIFT_LOGS]: 'Shift_Logs'
}

export const STAFF_TYPE = {
  OPERATOR: 'OPERATOR',
  SUPPORTER: 'SUPPORTER'
}

export const FILE_FORMAT_TYPE = {
  XLSX: 'EXCEL',
  CSV: 'CSV'
}
