import { USER_ROLE } from '@/config/constant';
import { BUY_ORDER_STEPS, SELL_ORDER_STEPS } from '@/constants/orders';

export const STATUS_PENDING_ORDER = '1,2,3'
export const STATUS_HISTORY_ORDER = '4,5'
export const STATUS_APPEAL_OPEN = '1'

export const LIST_POST_TYPE = [
  {
    name: 'common.buy',
    value: 'BUY'
  },
  {
    name: 'common.sell',
    value: 'SELL'
  }
]

export const LIST_SORT = [
  {
    name: 'common.filters.ascending',
    value: 'ASC'
  },
  {
    name: 'list_order.filters.decrease',
    value: 'DESC'
  }
]

export const LIST_PENDING_STATUS = [
  {
    name: 'common.status.undelivered',
    value: 1
  },
  {
    name: 'common.status.delivered',
    value: 3
  }
]

export const LIST_STATUS_HISTORY = [
  {
    name: 'common.status.complete',
    value: 4
  },
  {
    name: 'common.status.cancelled',
    value: 5
  }
]

export const ORDER_GROUPS = {
  WAITING: 'waiting',
  WAITING_USER: 'waiting_user',
  APPEAL: 'appeal',
  SUCCESS: 'success',
  CANCEL: 'cancel'
};

export const SELL_ORDER_GROUPS = {
  [USER_ROLE.USER]: {
    WAITING: [
      SELL_ORDER_STEPS.SELL_ORDER_CREATED_BY_USER,
      SELL_ORDER_STEPS.SELL_SENDING_CRYPTO_BY_USER,
      SELL_ORDER_STEPS.SELL_SENDING_CRYPTO_FAILED,
      SELL_ORDER_STEPS.SELL_SENDING_CRYPTO_SUCCESS,
      SELL_ORDER_STEPS.SELL_SENDING_CRYPTO_SUCCESS_DEAL_TIME,
      SELL_ORDER_STEPS.SELL_NOTIFY_SENT_FIAT_BY_MERCHANT_DEAL_TIME,
      SELL_ORDER_STEPS.SELL_ENABLE_APPEAL_NOTIFY_SENT_FIAT_BY_MERCHANT
    ],
    APPEAL: [
      SELL_ORDER_STEPS.SELL_APPEAL_SENT_FIAT_NOT_RECEIVED_BY_USER
    ],
    SUCCESS: [
      SELL_ORDER_STEPS.SELL_CONFIRMED_FIAT_BY_USER
    ],
    CANCEL: [
      SELL_ORDER_STEPS.SELL_ORDER_CANCELLED_BY_USER,
      SELL_ORDER_STEPS.SELL_ORDER_CANCELLED_BY_SYSTEM
    ]
  },
  [USER_ROLE.MERCHANT_OPERATOR]: {
    WAITING: [
      SELL_ORDER_STEPS.SELL_SENDING_CRYPTO_SUCCESS,
      SELL_ORDER_STEPS.SELL_SENDING_CRYPTO_SUCCESS_DEAL_TIME
    ],
    WAITING_USER: [
      SELL_ORDER_STEPS.SELL_ORDER_CREATED_BY_USER,
      SELL_ORDER_STEPS.SELL_SENDING_CRYPTO_BY_USER,
      SELL_ORDER_STEPS.SELL_SENDING_CRYPTO_FAILED,
      SELL_ORDER_STEPS.SELL_NOTIFY_SENT_FIAT_BY_MERCHANT_DEAL_TIME,
      SELL_ORDER_STEPS.SELL_ENABLE_APPEAL_NOTIFY_SENT_FIAT_BY_MERCHANT
    ],
    APPEAL: [
      SELL_ORDER_STEPS.SELL_APPEAL_SENT_FIAT_NOT_RECEIVED_BY_USER,
      SELL_ORDER_STEPS.SELL_NOTIFY_SENT_FIAT_BY_MERCHANT_DEAL_TIME
    ],
    SUCCESS: [
      SELL_ORDER_STEPS.SELL_CONFIRMED_FIAT_BY_USER
    ],
    CANCEL: [
      SELL_ORDER_STEPS.SELL_ORDER_CANCELLED_BY_USER,
      SELL_ORDER_STEPS.SELL_ORDER_CANCELLED_BY_SYSTEM
    ]
  },
  [USER_ROLE.MERCHANT_MANAGER]: {
    WAITING: [
      SELL_ORDER_STEPS.SELL_SENDING_CRYPTO_SUCCESS,
      SELL_ORDER_STEPS.SELL_SENDING_CRYPTO_SUCCESS_DEAL_TIME
    ],
    WAITING_USER: [
      SELL_ORDER_STEPS.SELL_ORDER_CREATED_BY_USER,
      SELL_ORDER_STEPS.SELL_SENDING_CRYPTO_BY_USER,
      SELL_ORDER_STEPS.SELL_SENDING_CRYPTO_FAILED,
      SELL_ORDER_STEPS.SELL_NOTIFY_SENT_FIAT_BY_MERCHANT_DEAL_TIME,
      SELL_ORDER_STEPS.SELL_ENABLE_APPEAL_NOTIFY_SENT_FIAT_BY_MERCHANT
    ],
    APPEAL: [
      SELL_ORDER_STEPS.SELL_APPEAL_SENT_FIAT_NOT_RECEIVED_BY_USER
    ],
    SUCCESS: [
      SELL_ORDER_STEPS.SELL_CONFIRMED_FIAT_BY_USER
    ],
    CANCEL: [
      SELL_ORDER_STEPS.SELL_ORDER_CANCELLED_BY_USER,
      SELL_ORDER_STEPS.SELL_ORDER_CANCELLED_BY_SYSTEM
    ]
  }
};

export const BUY_ORDER_GROUPS = {
  [USER_ROLE.USER]: {
    WAITING: [
      BUY_ORDER_STEPS.BUY_ORDER_CREATED_BY_USER,
      BUY_ORDER_STEPS.BUY_ORDER_CREATED_BY_USER_DEAL_TIME,
      BUY_ORDER_STEPS.BUY_NOTIFY_SENT_FIAT_BY_USER,
      BUY_ORDER_STEPS.BUY_NOTIFY_SENT_FIAT_BY_USER_DEAL_TIME,
      BUY_ORDER_STEPS.BUY_ENABLE_APPEAL_WHILE_CONFIRMING_FIAT_BY_MERCHANT,
      BUY_ORDER_STEPS.BUY_CONFIRMED_FIAT_BY_MERCHANT,
      BUY_ORDER_STEPS.BUY_CONFIRMED_FIAT_BY_MERCHANT_DEAL_TIME,
      BUY_ORDER_STEPS.BUY_SENDING_CRYPTO_BY_MERCHANT,
      BUY_ORDER_STEPS.BUY_SENDING_CRYPTO_FAILED
    ],
    APPEAL: [
      BUY_ORDER_STEPS.BUY_APPEAL_SENT_WHILE_CONFIRMING_FIAT_BY_MERCHANT,
      BUY_ORDER_STEPS.BUY_APPEAL_SENT_SENDING_CRYPTO_FAILED
    ],
    SUCCESS: [
      BUY_ORDER_STEPS.BUY_SENDING_CRYPTO_SUCCESS
    ],
    CANCEL: [
      BUY_ORDER_STEPS.BUY_ORDER_CANCELLED_BY_USER,
      BUY_ORDER_STEPS.BUY_ORDER_CANCELLED_BY_SYSTEM
    ]
  },
  [USER_ROLE.MERCHANT_OPERATOR]: {
    WAITING: [
      BUY_ORDER_STEPS.BUY_NOTIFY_SENT_FIAT_BY_USER,
      BUY_ORDER_STEPS.BUY_NOTIFY_SENT_FIAT_BY_USER_DEAL_TIME,
      BUY_ORDER_STEPS.BUY_ENABLE_APPEAL_WHILE_CONFIRMING_FIAT_BY_MERCHANT,
      BUY_ORDER_STEPS.BUY_CONFIRMED_FIAT_BY_MERCHANT,
      BUY_ORDER_STEPS.BUY_CONFIRMED_FIAT_BY_MERCHANT_DEAL_TIME,
      BUY_ORDER_STEPS.BUY_SENDING_CRYPTO_BY_MERCHANT,
      BUY_ORDER_STEPS.BUY_SENDING_CRYPTO_FAILED
    ],
    WAITING_USER: [
      BUY_ORDER_STEPS.BUY_ORDER_CREATED_BY_USER,
      BUY_ORDER_STEPS.BUY_ORDER_CREATED_BY_USER_DEAL_TIME
    ],
    APPEAL: [
      BUY_ORDER_STEPS.BUY_APPEAL_SENT_WHILE_CONFIRMING_FIAT_BY_MERCHANT,
      BUY_ORDER_STEPS.BUY_APPEAL_SENT_SENDING_CRYPTO_FAILED,
      BUY_ORDER_STEPS.BUY_ORDER_CREATED_BY_USER_DEAL_TIME
    ],
    SUCCESS: [
      BUY_ORDER_STEPS.BUY_SENDING_CRYPTO_SUCCESS
    ],
    CANCEL: [
      BUY_ORDER_STEPS.BUY_ORDER_CANCELLED_BY_USER,
      BUY_ORDER_STEPS.BUY_ORDER_CANCELLED_BY_SYSTEM
    ]
  },
  [USER_ROLE.MERCHANT_MANAGER]: {
    WAITING: [
      BUY_ORDER_STEPS.BUY_NOTIFY_SENT_FIAT_BY_USER,
      BUY_ORDER_STEPS.BUY_NOTIFY_SENT_FIAT_BY_USER_DEAL_TIME,
      BUY_ORDER_STEPS.BUY_ENABLE_APPEAL_WHILE_CONFIRMING_FIAT_BY_MERCHANT,
      BUY_ORDER_STEPS.BUY_CONFIRMED_FIAT_BY_MERCHANT,
      BUY_ORDER_STEPS.BUY_CONFIRMED_FIAT_BY_MERCHANT_DEAL_TIME,
      BUY_ORDER_STEPS.BUY_SENDING_CRYPTO_BY_MERCHANT,
      BUY_ORDER_STEPS.BUY_SENDING_CRYPTO_FAILED
    ],
    WAITING_USER: [
      BUY_ORDER_STEPS.BUY_ORDER_CREATED_BY_USER,
      BUY_ORDER_STEPS.BUY_ORDER_CREATED_BY_USER_DEAL_TIME
    ],
    APPEAL: [
      BUY_ORDER_STEPS.BUY_APPEAL_SENT_WHILE_CONFIRMING_FIAT_BY_MERCHANT,
      BUY_ORDER_STEPS.BUY_APPEAL_SENT_SENDING_CRYPTO_FAILED
    ],
    SUCCESS: [
      BUY_ORDER_STEPS.BUY_SENDING_CRYPTO_SUCCESS
    ],
    CANCEL: [
      BUY_ORDER_STEPS.BUY_ORDER_CANCELLED_BY_USER,
      BUY_ORDER_STEPS.BUY_ORDER_CANCELLED_BY_SYSTEM
    ]
  }
};
